
"""#38-mourodev-pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QD6r-2pvRV1RgmkqXQWAlZJc-knZLOkg

/*
 * EJERCICIO:
 * He presentado mi proyecto más importante del año: mouredev pro.
 * Un campus para la comunidad, que lanzaré en octubre, donde estudiar
 * programación de una manera diferente.
 * Cualquier persona suscrita a la newsletter de https://mouredev.pro
 * accederá a sorteos mensuales de suscripciones, regalos y descuentos.
 *
 * Desarrolla un programa que lea los registros de un fichero .csv y
 * seleccione de manera aleatoria diferentes ganadores.
 * Requisitos:
 * 1. Crea un .csv con 3 columnas: id, email y status con valor "activo"
 *    o "inactivo" (y datos ficticios).
 *    Ejemplo: 1 | test@test.com | activo
 *             2 | test2@test.com | inactivo
 *    (El .csv no debe subirse como parte de la corrección)
 * 2. Recupera los datos desde el programa y selecciona email aleatorios.
 * Acciones:
 * 1. Accede al fichero .csv y selecciona de manera aleatoria un email
 *    ganador de una suscripción, otro ganador de un descuento y un último
 *    ganador de un libro (sólo si tiene status "activo" y no está repetido).
 * 2. Muestra los emails ganadores y su id.
 * 3. Ten en cuenta que la primera fila (con el nombre de las columnas)
 *    no debe tenerse en cuenta.
 */
'''
"""

import pandas as pd
import random

fichero = pd.read_csv('./test.csv')

def seleccionar_ganador(archivo):
  df_activos = archivo[archivo['status'] == 'activo']
  if not df_activos.empty:
    ganador_indice = random.randint(0, len(df_activos) - 1)
    ganador = df_activos.iloc[ganador_indice]
    return ganador['id'], ganador['email']
  else:
    return None, None


ganador_suscripcion_id, ganador_suscripcion_email = seleccionar_ganador(fichero)
ganador_descuento_id, ganador_descuento_email = seleccionar_ganador(fichero)
ganador_libro_id, ganador_libro_email = seleccionar_ganador(fichero)


print("Ganador de suscripción:")
if ganador_suscripcion_email:
  print("ID:", ganador_suscripcion_id, ", Email:", ganador_suscripcion_email)
else:
  print("No hay ganadores activos.")

print("\nGanador de descuento:")
if ganador_descuento_email:
  print("ID:", ganador_descuento_id, ", Email:", ganador_descuento_email)
else:
  print("No hay ganadores activos.")

print("\nGanador de libro:")
if ganador_libro_email:
  print("ID:", ganador_libro_id, ", Email:", ganador_libro_email)
else:
  print("No hay ganadores activos.")