#  * EJERCICIO:
#  * - Crea un comentario en el código y coloca la URL del sitio web oficial del
#  *   lenguaje de programación que has seleccionado.
#  * - Representa las diferentes sintaxis que existen de crear comentarios
#  *   en el lenguaje (en una línea, varias...).
#  * - Crea una variable (y una constante si el lenguaje lo soporta).
#  * - Crea variables representando todos los tipos de datos primitivos
#  *   del lenguaje (cadenas de texto, enteros, booleanos...).
#  * - Imprime por terminal el texto: "¡Hola, [y el nombre de tu lenguaje]!"
#  *
#  * ¿Fácil? No te preocupes, recuerda que esta es una ruta de estudio y
#  * debemos comenzar por el principio.
#  */


# https://www.python.org/


# Comentario Simple(Una linea)
"""Comentario de varias lineas(comillas dobles)
"""


'''Comentarios de varias lineas(comillas simples)'''



#* Variable y Constante
nombre ="Pedro"
PI = 3.14 # Como tal no es una constante, pero es lo mas cercano



#* Tipos de Variables
cadena = "Hola Mundo"
entero = 30
flotante = 10
boleano = True
nulo = None
# Para saber el tipo de variable
print(type(cadena))
print(type(entero))
print(type(boleano))
print(type(nulo))


print("¡Hola, Python!")
