const actual: Date = new Date()
const birthdayDate: Date = new Date('2002-12-17')

let years: number = actual.getFullYear() - birthdayDate.getFullYear()
console.log(years)

const date: Date = new Date()
console.log(`${date.getDate()}/${date.getMonth() + 1}/${date.getFullYear()}`)
console.log(`${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`)
console.log(`${date.getFullYear()}/${date.getMonth() + 1}/${date.getDate()}`)
console.log(`${date.getHours()}/${date.getMinutes()}/${date.getSeconds()}`)
console.log(`${date.getSeconds()}/${date.getMinutes()}/${date.getHours()}`)
console.log(`${date.getMinutes()}/${date.getSeconds()}/${date.getHours()}`)
console.log(`${date.getMinutes()}`)
console.log(`${date.getHours()}`)
console.log(`${date.getSeconds()}`)
console.log(`${date.getMonth()}`)
console.log(`${date.getFullYear()}`)
console.log(`${date.getDate()}`)